const view /** HTML */ = `
<h2>O QUE É SUBSCRIÇÃO DE SEGUROS</h2>
  <p>Ao segurar indivíduos, famílias e organizações, as seguradoras assumem riscos de bilhões de reais a cada ano. O processo pelo qual aceitam ou rejeitam novos contratos e renovações de contratos antigos se chama subscrição (em inglês, underwriting) e envolve várias etapas e ferramentas. </p>
<p>O objetivo da subscrição é manter a lucratividade da seguradora ao longo do tempo. A qualidade de processo de subscrição e os resultados favoráveis daí resultantes são necessários para que a firma cresça a longo prazo. </p>
<h3>Lucratividade</h3><br>
<p>Uma companhia de seguros deve obter um lucro adequado se deseja aumentar a venda de seguros. A capacidade de gerar prêmios é limitada por normas regulatórias e, muitas vezes, por restrições voluntárias até mais restritivas. </p>
<p>Se as práticas de subscrição geram contratos cujos prêmios excedem as indenizações e demais despesas, o lucro subsequente elevará a capacidade da seguradora. Os subscritores asseguram lucros adequados à companhia ao aderirem a diretrizes de subscrição emanadas da direção da seguradora. Estas devem garantir precisa identificação e avaliação dos riscos e cobrança de prêmios de seguros atuarialmente corretos. </p>
<h3>Responsabilidades do subscritor</h3><br>
<p>Os subscritores devem revisar a proposta de seguro e, em seguida, fixar a taxa apropriada, ou rejeitar a proposta. Diretrizes preestabelecidas podem, por exemplo, restringir a aceitação de seguros de automóveis de motoristas com menos de 21 anos de idade ou de seguros residenciais em áreas de furacão, mas, em cada caso, a decisão depende muito experiência e julgamento pessoais. </p>
<p>O subscritor deve também ser capaz de julgar as intenções do segurado. Se a moral do candidato for questionável, o subscritor provavelmente recusará o seguro, independente da solidez da sua empresa ou da sua saúde. </p>

<h3>Seleção Adversa</h3><br>
<p>O processo de subscrição deve proteger a seguradora da seleção adversa. Os subscritores devem estar sempre atentos a essa possibilidade. A seleção adversa decorre da maior probabilidade das pessoas que optam por adquirir seguros de sofrerem sinistros cujas esperanças matemáticas (expectativas de indenização) superam os prêmios que pagam. </p>
<p>Esta é uma característica comum no mercado de seguros. Sabe-se, por exemplo, da tendência de proprietários de casas em áreas de tempestades de comprar seguro às vésperas de uma temporada de furacões. Ou de pessoas que compram planos de saúde quando antecipam uma doença mais grave. </p>
<p>Se há seleção adversa, o grupo de segurados terá um viés de alto risco e o subscritor que não os seleciona cuidadosamente obterá sinistralidade acima do previsto. Em alguns casos, as seguradoras aceitam tais exposições, mas cobram prêmios maiores que refletem o aumento esperado no custo dos sinistros. Aceitar riscos elevados e não cobrar prêmios mais altos gera prejuízo e pode resultar na falência da seguradora. Reconhecendo a possibilidade sempre presente da seleção, o subscritor deve examinar cuidadosamente todas as propostas de seguro. Classificar adequadamente os riscos e lidar com a seleção adversa potencial são a essência da atividade do subscritor. </p>

`;
let Session_08 = {
    render: async () => view,
    after_render: async () => { }
}

export default Session_08;